# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24e29551d27b3f7c9c913b49b10e0c7c0d0c22b05234bdd712dc08e4cb135e6af2e297d2d5223bec783a56e9d3774d441565788a7a03234d340f4c4b0ff54653

test:
  secret_key_base: 272215dca92ba9628a5201c9c9ceb9a2530adf9c317a499d2a040aa1ba3ee3d75e5ca63ef9bb997ba5405f92b1f6ef86e8b156139488d2230bf0fd0824f997db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
